/* eslint-disable */

const AVAILABLE_NOTES = [2000, 500, 100, 20, 10, 5, 1];

const NO_OF_EACH_AVAILABLE_NOTES = [];
AVAILABLE_NOTES.forEach((note) => NO_OF_EACH_AVAILABLE_NOTES.push(""));

export { AVAILABLE_NOTES, NO_OF_EACH_AVAILABLE_NOTES };
